name: Greeter
description: Greeter indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: Factory
    abi_file_path: ./abis/factory.json
    handler: ./src/EventHandlers.ts
    events:
      - event: PoolCreated
        requiredEntities:
          - name: Pool
networks:
  - id: 142 # Shimmer
    start_block: 35196
    rpc_config:
      url: "http://127.0.0.1:3113"
    contracts:
      - name: Factory #A reference to the global contract definition
        address: 0xdf7bA717FB0D5ce579252f05167cD96d0fA77bCb
