name: Greeter
description: Greeter indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: Factory
    abi_file_path: ./abis/factory.json
    handler: ./src/event-handlers/Factory.ts
    events:
      - event: PoolCreated
        isAsync: true
        requiredEntities:
          - name: Pool
          - name: Factory
          - name: Token
          - name: TokenPoolWhitelist
networks:
  - id: 148 # Shimmer
    start_block: 35196
    contracts:
      - name: Factory #A reference to the global contract definition
        address: 0xdf7bA717FB0D5ce579252f05167cD96d0fA77bCb
